const DAILY_BASE_REWARD = 100;
const DAILY_COOLDOWN_HOURS = 20;
const DAILY_STREAK_RESET_HOURS = 48;
const DAILY_STREAK_BONUS_PER_DAY = 10;
const DAILY_STREAK_BONUS_CAP = 100;
const TOP_DINERO_LIMIT = 10;

module.exports = {
  DAILY_BASE_REWARD,
  DAILY_COOLDOWN_HOURS,
  DAILY_STREAK_RESET_HOURS,
  DAILY_STREAK_BONUS_PER_DAY,
  DAILY_STREAK_BONUS_CAP,
  TOP_DINERO_LIMIT,
};
