// @ts-nocheck
module.exports = [
  {
    id: "class_centinela",
    name: "Centinela",
    role: "defensivo",
    description: "Defensor firme que protege a sus aliados con resistencia y control de masas.",
    bonuses: { defensa: 20, fuerza: 10, vida: 30 },
    penalties: { agilidad: -5 },
    baseSkills: ["golpe_poderoso", "escudo_defensivo", "postura_ferrea"],
    restrictions: [],
    synergies: ["class_custodio", "class_paladin"],
    lore: "Los centinelas son la muralla inquebrantable de cualquier grupo, entrenados para resistir embates y proteger a los más débiles con su propia carne.",
  },
  {
    id: "class_custodio",
    name: "Custodio",
    role: "soporte",
    description: "Protector y sanador que vela por el bienestar del grupo con luz y fe.",
    bonuses: { defensa: 15, carisma: 10, magia: 10 },
    penalties: { fuerza: -5 },
    baseSkills: ["curacion_basica", "escudo_sagrado", "proteccion_grupal"],
    restrictions: [],
    synergies: ["class_centinela", "class_clerigo"],
    lore: "Los custodios canalizan poder divino para sostener a sus compañeros, curando heridas y bendiciendo sus armas en la batalla.",
  },
  {
    id: "class_paladin",
    name: "Paladín",
    role: "defensivo",
    description: "Guerrero sagrado que combina fe, defensa y daño híbrido en una sola causa.",
    bonuses: { defensa: 15, fuerza: 10, magia: 5 },
    penalties: { agilidad: -5 },
    baseSkills: ["golpe_sagrado", "escudo_defensivo", "luz_curativa"],
    restrictions: [
      { type: "race", value: "race_demon", reason: "Los paladines juran lealtad a la luz y rechazan a los demonios." },
      {
        type: "race",
        value: "race_undead",
        reason: "Los paladines juran lealtad a la luz y rechazan a los no muertos.",
      },
      {
        type: "race",
        value: "race_void",
        reason: "Los paladines juran lealtad a la luz y rechazan a los seres del vacío.",
      },
      {
        type: "race",
        value: "race_vampire",
        reason: "Los paladines juran lealtad a la luz y rechazan a los vampiros.",
      },
      { type: "race", value: "race_puppet", reason: "Los paladines juran lealtad a la luz y rechazan a los puppets." },
      { type: "race", value: "race_oni", reason: "Los paladines juran lealtad a la luz y rechazan a los onis." },
    ],
    synergies: ["class_centinela", "class_clerigo"],
    lore: "Los paladines son campeones de la luz que combinan disciplina marcial con devoción divina, castigando a las fuerzas de la oscuridad.",
  },
  {
    id: "class_guerrero",
    name: "Guerrero",
    role: "ofensivo",
    description: "Combatiente versátil con entrenamiento físico equilibrado para cualquier enfrentamiento.",
    bonuses: { fuerza: 15, defensa: 10 },
    penalties: { magia: -5 },
    baseSkills: ["golpe_poderoso", "postura_defensiva"],
    restrictions: [],
    synergies: ["class_berserker", "class_barbaro"],
    lore: "Los guerreros son la columna vertebral de todo ejército, maestros en el arte del combate cuerpo a cuerpo con armas y escudos.",
  },
  {
    id: "class_berserker",
    name: "Berserker",
    role: "ofensivo",
    description: "Luchador impulsivo que sacrifica defensa por un poder ofensivo devastador.",
    bonuses: { fuerza: 25 },
    penalties: { defensa: -10, carisma: -5 },
    baseSkills: ["furia_berserker", "golpe_poderoso", "grito_de_guerra"],
    restrictions: [],
    synergies: ["class_guerrero", "class_barbaro"],
    lore: "Los berserkers entran en trances de furia incontrolable que multiplican su fuerza bruta, ignorando el dolor y el miedo en combate.",
  },
  {
    id: "class_destructor",
    name: "Destructor",
    role: "ofensivo",
    description: "Especialista en derribar estructuras, armaduras y obstáculos con fuerza demoledora.",
    bonuses: { fuerza: 20, defensa: 10 },
    penalties: { agilidad: -10 },
    baseSkills: ["golpe_poderoso", "romper_armadura", "golpe_devastador"],
    restrictions: [],
    synergies: ["class_berserker"],
    lore: "Los destructores están hechos para romper todo a su paso, entrenados para derribar murallas y devastar formaciones enemigas.",
  },
  {
    id: "class_barbaro",
    name: "Bárbaro",
    role: "ofensivo",
    description: "Salvaje guerrero que desata daño físico bruto con poca técnica pero gran ferocidad.",
    bonuses: { fuerza: 20, agilidad: 10 },
    penalties: { magia: -10, carisma: -5 },
    baseSkills: ["golpe_poderoso", "furia_berserker", "grito_de_guerra"],
    restrictions: [],
    synergies: ["class_berserker", "class_guerrero"],
    lore: "Los bárbaros provienen de tierras salvajes donde la fuerza y la supervivencia son la única ley, despreciando la civilización y la magia.",
  },
  {
    id: "class_acechador",
    name: "Acechador",
    role: "sigilo",
    description: "Asesino silencioso que golpea desde las sombras con evasión y golpes críticos.",
    bonuses: { agilidad: 20, percepcion: 15 },
    penalties: { defensa: -10, fuerza: -5 },
    baseSkills: ["ataque_sigiloso", "golpe_critico", "evasion"],
    restrictions: [],
    synergies: ["class_picaro", "class_errante"],
    lore: "Los acechadores se mueven como sombras vivientes, apareciendo de la nada para asestar golpes mortales antes de desaparecer.",
  },
  {
    id: "class_picaro",
    name: "Pícaro",
    role: "sigilo",
    description: "Ladrón y trampero astuto que usa precisión y engaños para vencer a sus enemigos.",
    bonuses: { agilidad: 15, percepcion: 10 },
    penalties: { defensa: -10, magia: -5 },
    baseSkills: ["ataque_sigiloso", "colocar_trampa", "golpe_preciso"],
    restrictions: [],
    synergies: ["class_acechador", "class_errante"],
    lore: "Los pícaros viven al filo de la ley, usando su ingenio y agilidad para superar cualquier obstáculo con trampas y engaños.",
  },
  {
    id: "class_ranger",
    name: "Ranger",
    role: "sigilo",
    description: "Explorador letal a distancia con instintos de supervivencia y rastreo superiores.",
    bonuses: { percepcion: 20, agilidad: 15, fuerza: 5 },
    penalties: { magia: -5 },
    baseSkills: ["disparo_preciso", "rastreo", "supervivencia"],
    restrictions: [],
    synergies: ["class_acechador", "class_druida"],
    lore: "Los rangers son maestros del terreno que combinan puntería letal con un conocimiento profundo de la naturaleza y sus criaturas.",
  },
  {
    id: "class_errante",
    name: "Errante",
    role: "ofensivo",
    description: "Versátil aventurero sin especialización fija que se adapta a cualquier situación.",
    bonuses: { fuerza: 10, agilidad: 10, defensa: 5 },
    penalties: { magia: -3 },
    baseSkills: ["golpe_poderoso", "ataque_sigiloso", "escapada"],
    restrictions: [],
    synergies: ["class_acechador", "class_picaro", "class_ranger"],
    lore: "Los errantes recorren el mundo sin ataduras, acumulando experiencias que los convierten en combatientes impredecibles y versátiles.",
  },
  {
    id: "class_mago",
    name: "Mago",
    role: "magico",
    description: "Erudito de las artes arcanas que domina la magia a través del estudio y la disciplina.",
    bonuses: { magia: 20, percepcion: 10 },
    penalties: { fuerza: -10, defensa: -5 },
    baseSkills: ["rafo_magico", "escudo_arcano", "intelecto_arcano"],
    restrictions: [],
    synergies: ["class_arcanista", "class_hechicero"],
    lore: "Los magos pasan décadas en bibliotecas y torres estudiando los secretos del arcano para dominar hechizos de poder incalculable.",
  },
  {
    id: "class_hechicero",
    name: "Hechicero",
    role: "magico",
    description: "Canalizador de magia innata que despliega poder bruto con su voluntad y carisma.",
    bonuses: { magia: 20, carisma: 10 },
    penalties: { fuerza: -10, defensa: -5 },
    baseSkills: ["rafo_magico", "voluntad_ferrea", "explosion_mana"],
    restrictions: [],
    synergies: ["class_mago", "class_brujo"],
    lore: "Los hechiceros nacen con la magia corriendo por sus venas, heredando un poder que otros solo pueden alcanzar con años de estudio.",
  },
  {
    id: "class_brujo",
    name: "Brujo",
    role: "magico",
    description: "Portador de magia obtenida mediante pactos oscuros con entidades de otros planos.",
    bonuses: { magia: 20, carisma: 10 },
    penalties: { fuerza: -5, percepcion: -5 },
    baseSkills: ["rafo_oscuro", "drenar_vida", "pacto_oscuro"],
    restrictions: [],
    synergies: ["class_hechicero", "class_sombramante"],
    lore: "Los brujos obtienen su poder mediante tratos con entidades superiores, intercambiando lealtad o servicios por conocimientos arcanos prohibidos.",
  },
  {
    id: "class_arcanista",
    name: "Arcanista",
    role: "magico",
    description: "Manipulador de energía pura que canaliza el mana en su estado más elemental.",
    bonuses: { magia: 25, percepcion: 10 },
    penalties: { fuerza: -15, defensa: -10 },
    baseSkills: ["rafo_magico", "explosion_mana", "escudo_arcano"],
    restrictions: [],
    synergies: ["class_mago", "class_oraculo"],
    lore: "Los arcanistas manipulan la energía mágica en su estado más puro, desatando torrentes de poder que pocos pueden siquiera comprender.",
  },
  {
    id: "class_sombramante",
    name: "Sombramante",
    role: "magico",
    description: "Invocador de sombras que debilita a sus enemigos con magia oscura y sigilo.",
    bonuses: { magia: 15, agilidad: 10 },
    penalties: { carisma: -5, fuerza: -5 },
    baseSkills: ["rafo_oscuro", "sombras_envolvientes", "debilitar"],
    restrictions: [
      {
        type: "alignment",
        value: ["oscuridad", "vacio"],
        reason: "Los sombramantes requieren afinidad con la oscuridad o el vacío.",
      },
    ],
    synergies: ["class_brujo", "class_picaro"],
    lore: "Los sombramantes tejen la oscuridad misma como un arma, sumiendo a sus enemigos en tinieblas mientras drenan su voluntad y energía.",
  },
  {
    id: "class_oraculo",
    name: "Oráculo",
    role: "soporte",
    description: "Vidente que manipola la probabilidad y el destino para guiar a sus aliados.",
    bonuses: { percepcion: 25, magia: 10, carisma: 5 },
    penalties: { fuerza: -10, defensa: -10 },
    baseSkills: ["vision_de_futuro", "premonicion", "rafo_magico"],
    restrictions: [],
    synergies: ["class_arcanista", "class_custodio"],
    lore: "Los oráculos poseen la capacidad de vislumbrar fragmentos del futuro, inclinando las probabilidades a favor de sus aliados en momentos cruciales.",
  },
  {
    id: "class_clerigo",
    name: "Clérigo",
    role: "soporte",
    description: "Devoto de la luz que sana heridas y protege al grupo con milagros sagrados.",
    bonuses: { magia: 15, carisma: 15, defensa: 5 },
    penalties: { fuerza: -10, agilidad: -5 },
    baseSkills: ["curacion_basica", "luz_sagrada", "escudo_sagrado"],
    restrictions: [
      { type: "race", value: "race_demon", reason: "Los clérigos sirven a la luz y rechazan a los demonios." },
      { type: "race", value: "race_undead", reason: "Los clérigos sirven a la luz y rechazan a los no muertos." },
      { type: "race", value: "race_void", reason: "Los clérigos sirven a la luz y rechazan a los seres del vacío." },
      { type: "race", value: "race_vampire", reason: "Los clérigos sirven a la luz y rechazan a los vampiros." },
      { type: "race", value: "race_puppet", reason: "Los clérigos sirven a la luz y rechazan a los puppets." },
      { type: "race", value: "race_oni", reason: "Los clérigos sirven a la luz y rechazan a los onis." },
    ],
    synergies: ["class_custodio", "class_paladin"],
    lore: "Los clérigos son siervos de la luz divina que dedican su vida a sanar, proteger y guiar a los necesitados con fe inquebrantable.",
  },
  {
    id: "class_druida",
    name: "Druida",
    role: "soporte",
    description: "Guardián de la naturaleza que usa magia primal para regenerar y proteger.",
    bonuses: { magia: 10, defensa: 10, percepcion: 10 },
    penalties: { carisma: -5 },
    baseSkills: ["curacion_basica", "llamado_de_la_naturaleza", "piel_de_corteza"],
    restrictions: [],
    synergies: ["class_ranger", "class_custodio"],
    lore: "Los druidas son los protectores del equilibrio natural, capaces de tomar la fuerza de la tierra y los bosques para sanar o defender.",
  },
  {
    id: "class_alquimista",
    name: "Alquimista",
    role: "tecnico",
    description: "Maestro de pociones, venenos y mejoras que apoya al grupo con sus creaciones.",
    bonuses: { percepcion: 20, carisma: 10 },
    penalties: { fuerza: -10, defensa: -5 },
    baseSkills: ["preparar_veneno", "pocion_curativa", "analisis"],
    restrictions: [],
    synergies: ["class_picaro", "class_mago"],
    lore: "Los alquimistas transforman ingredientes ordinarios en poderosos elixires, venenos letales y mejoras temporales que cambian el curso de la batalla.",
  },
  {
    id: "class_ingeniero_arcano",
    name: "Ingeniero Arcano",
    role: "tecnico",
    description: "Creador de artefactos mágicos y dispositivos mecánicos con aplicaciones de combate.",
    bonuses: { percepcion: 20, fuerza: 5, defensa: 5 },
    penalties: { magia: -10, carisma: -5 },
    baseSkills: ["construir_trampa", "reparar_dispositivo", "analisis"],
    restrictions: [],
    synergies: ["class_alquimista"],
    lore: "Los ingenieros arcanos fusionan tecnología y magia para crear artefactos únicos, desde trampas ingeniosas hasta dispositivos de poder inimaginable.",
  },
  {
    id: "class_vinculo",
    name: "Vínculo",
    role: "soporte",
    description: "Invocador que establece lazos espirituales con entidades de otros planos.",
    bonuses: { carisma: 20, magia: 15 },
    penalties: { fuerza: -10, defensa: -5 },
    baseSkills: ["invocar_espiritu", "vincular_entidad", "curacion_basica"],
    restrictions: [],
    synergies: ["class_brujo", "class_druida"],
    lore: "Los vinculados forjan conexiones profundas con espíritus y entidades de otros reinos, invocándolos para que luchen a su lado.",
  },
];
